name: Publish Authenticator GitHub Release as newest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * 1-5' # Every hour on the hour on weekdays

permissions:
  contents: write
  actions: write
  id-token: write

jobs:
  publish-release-authenticator:
    name: Publish Authenticator Release
    uses: bitwarden/gh-actions/.github/workflows/_publish-mobile-github-release.yml@main
    with:
      release_name: "Authenticator"
      workflow_name: "publish-github-release-bwa.yml"
      credentials_filename: "appstoreconnect-fastlane.json"
      project_type: ios
      make_latest: false
      check_release_command: >
        bundle exec fastlane ios get_latest_version api_key_path:$CREDENTIALS_PATH app_identifier:com.bitwarden.authenticator
    secrets: inherit
